/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.entities.Train;
import org.example.entities.User;
import org.example.services.UserBookingService;
import org.example.util.UserServiceUtil;

import java.util.*;

public class App {

    public static void main(String[] args) {
           System.out.println("Running train booking system");
        Scanner scanner = new Scanner(System.in);
        int option =0;
        UserBookingService userBookingService;
        try{
         userBookingService=new UserBookingService();

        }catch(Exception e){
            System.out.println("There is something wrong with the user booking service");
            return;

        }
        while(option!=7){
            System.out.println("Please enter your option");
            System.out.println("1. Create a new user");
            System.out.println("2.Login");
            System.out.println("3.Fetch Bookings");
            System.out.println("4.Search Trains");
            System.out.println("5.Book a seat");
            System.out.println("6.Cancael a booking");
            System.out.println("7.Exit");
            option=scanner.nextInt();
            Train trainSelectedForBooking = new Train();
            switch(option){
                case 1:
                    System.out.println("Please enter your username");
                    String username=scanner.next();
                    System.out.println("Please enter your password");
                    String password=scanner.next();
                    User userToSignUp=new User(username,password, UserServiceUtil.hashPassword(password),new ArrayList<>(), UUID.randomUUID().toString());
                    userBookingService.signUp(userToSignUp);
                    break;

                    case 2:
                        System.out.println("Please enter your username");
                        String name=scanner.next();
                        System.out.println("Please enter your password");
                        String passwordtologin=scanner.next();
                        User userToLogin=new User(name,passwordtologin, UserServiceUtil.hashPassword(passwordtologin),new ArrayList<>(), UUID.randomUUID().toString());
                        try{
                            userBookingService=new UserBookingService(userToLogin);

                        }catch(Exception e){
                            return;
                        }
                        break;
                        case 3:
                            System.out.println("fetching ur bookings");
                            userBookingService.fetchBookings();
                            break;
                            case 4:
                                System.out.println("Type ur source station");
                                String source=scanner.next();
                                System.out.println("Type ur destination station");
                                String destination=scanner.next();
                                List<Train>trains=userBookingService.getTrains(source,destination);
                                int index=1;
                                for(Train train:trains){
                                    System.out.println(index+"Train id"+ train.getTrainId());
                                    for(Map.Entry<String,String>entry: train.getStationTimes().entrySet()){
                                        System.out.println(entry.getKey()+"\t"+entry.getValue());
                                    }
                                }
                                System.out.println("Select a train by typing 1,2 ,3");
                               trainSelectedForBooking=trains.get(scanner.nextInt());
                               break;
                               case 5:
                                   System.out.println("Select a seat out of these seats");
                                   List<List<Integer>> seats = userBookingService.fetchSeats(trainSelectedForBooking);
                                   for (List<Integer> row: seats){
                                       for (Integer val: row){
                                           System.out.print(val+" ");
                                       }
                                       System.out.println();
                                   }
                                   System.out.println("Select the seat by typing the row and column");
                                   System.out.println("Enter the row");
                                   int row = scanner.nextInt();
                                   System.out.println("Enter the column");
                                   int col = scanner.nextInt();
                                   System.out.println("Booking your seat....");
                                   Boolean booked = userBookingService.bookTrainSeat(trainSelectedForBooking, row, col);
                                   if(booked.equals(Boolean.TRUE)){
                                       System.out.println("Booked! Enjoy your journey");
                                   }else{
                                       System.out.println("Can't book this seat");
                                   }
                                   break;
                default:
                    break;
            }
        }
    }
}
